"""Quest data model for AI-generated fortress challenges.

Quests are generated by the LLM based on actual fortress state and must be
achievable in Dwarf Fortress. Categories cover the main gameplay pillars.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class QuestCategory(str, Enum):
    MILITARY = "military"
    CONSTRUCTION = "construction"
    RELIGIOUS = "religious"
    CRAFTING = "crafting"
    EXPLORATION = "exploration"
    SOCIAL = "social"
    CHAOS = "chaos"


class QuestDifficulty(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    LEGENDARY = "legendary"


class QuestStatus(str, Enum):
    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class Quest(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    title: str
    description: str
    category: QuestCategory
    difficulty: QuestDifficulty = QuestDifficulty.MEDIUM
    status: QuestStatus = QuestStatus.ACTIVE
    priority: bool = False

    game_year: int = 0
    game_season: str = ""
    created_at: datetime = Field(default_factory=datetime.now)
    completed_at: datetime | None = None

    # Fortress state summary when quest was created (for completion narrative context)
    context_snapshot: str = ""

    # AI-generated completion narrative
    completion_narrative: str = ""

    # Player hints on how to achieve the quest in-game
    hints: list[str] = Field(default_factory=list)

    # Dwarves the quest relates to
    related_unit_names: list[str] = Field(default_factory=list)
